name: pixeda-backend
services:
  - name: api
    type: web
    git:
      branch: main
      build_command: npm ci
      run_command: npm start
    instance_type: nano
    scaling:
      min: 1
      max: 1
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    health_check:
      path: /health
      port: 8000
    regions:
      - fra
